//
// Created by Colby on 6/16/2022.
//

#ifndef DYNAMICPROGRAMMINGALGORITHMS_DIVIDECONQUER_H
#define DYNAMICPROGRAMMINGALGORITHMS_DIVIDECONQUER_H

int dcBinomialCoeff(int n, int k);
void logDcResult();

#endif //DYNAMICPROGRAMMINGALGORITHMS_DIVIDECONQUER_H
