//
// Created by dxfan on 6/16/2022.
//

#ifndef DYNAMICPROGRAMMINGALGORITHMS_DYNAMICPROGRAMMING_H
#define DYNAMICPROGRAMMINGALGORITHMS_DYNAMICPROGRAMMING_H

int dpBinomialCoeff(int n, int k);
void logDpResult();
int min(int a, int b);

#endif //DYNAMICPROGRAMMINGALGORITHMS_DYNAMICPROGRAMMING_H
